function plotting_create_3figures(Y1, Y2, Y3)
%CREATEFIGURE1(Y1, Y2, Y3)
%  Y1:  vector of y data
%  Y2:  vector of y data
%  Y3:  vector of y data

%  Auto-generated by MATLAB on 24-May-2020 20:12:42

% Create figure
figure('OuterPosition',[570 137 948 884]);

% Create subplot
subplot1 = subplot(3,1,1);
hold(subplot1,'on');

% Create plot
plot(Y1,'LineWidth',1,'Color',[0 0 0]);

box(subplot1,'on');
% Set the remaining axes properties
set(subplot1,'FontSize',14,'FontWeight','bold','LineWidth',1);
% Create subplot
subplot2 = subplot(3,1,2);
hold(subplot2,'on');

% Create plot
plot(Y2,'LineWidth',1,'Color',[0 0 0]);

box(subplot2,'on');
% Set the remaining axes properties
set(subplot2,'FontSize',14,'FontWeight','bold','LineWidth',1);
% Create subplot
subplot3 = subplot(3,1,3);
hold(subplot3,'on');

% Create plot
plot(Y3,'LineWidth',1,'Color',[0 0 0]);

box(subplot3,'on');
% Set the remaining axes properties
set(subplot3,'FontSize',14,'FontWeight','bold','LineWidth',1);
