function RGB_3fig(Y1, Y2, Y3)
%CREATEFIGURE(Y1, Y2, Y3)
%  Y1:  vector of y data
%  Y2:  vector of y data
%  Y3:  vector of y data

%  Auto-generated by MATLAB on 26-May-2020 21:58:31

% Create figure
figure('OuterPosition',[435 144 961 901]);

% Create subplot
subplot1 = subplot(3,1,1);
hold(subplot1,'on');

% Create plot
plot(Y1,'LineWidth',1.5,'Color',[0 0 0]);

% Create xlabel
xlabel({'(a)'});

box(subplot1,'on');
% Set the remaining axes properties
set(subplot1,'FontSize',16,'FontWeight','bold','LineWidth',1.3);
% Create subplot
subplot2 = subplot(3,1,2);
hold(subplot2,'on');

% Create plot
plot(Y2,'LineWidth',1.5,'Color',[0 0 0]);

% Create xlabel
xlabel({'(b)'});

box(subplot2,'on');
% Set the remaining axes properties
set(subplot2,'FontSize',16,'FontWeight','bold','LineWidth',1.3);
% Create subplot
subplot3 = subplot(3,1,3);
hold(subplot3,'on');

% Create plot
plot(Y3,'LineWidth',1.5,'Color',[0 0 0]);

% Create xlabel
xlabel({'(c)','No. of Samples'});

box(subplot3,'on');
% Set the remaining axes properties
set(subplot3,'FontSize',16,'FontWeight','bold','LineWidth',1.3);
